#!/bin/bash

# Kancer The Crab - Image Download Helper
# This script helps download images from various sources

echo "🦀 Kancer The Crab - Image Download Helper"
echo "=========================================="
echo ""
echo "Since Instagram and other sites block automated scraping,"
echo "here's how to manually download your images:"
echo ""
echo "METHOD 1: Browser Extension (Recommended)"
echo "------------------------------------------"
echo "1. Install 'Image Downloader' extension in Chrome/Firefox"
echo "2. Visit: https://www.instagram.com/kancerthecrab"
echo "3. Click the extension icon and download all images"
echo "4. Save them to: images/ folder in this project"
echo ""
echo "METHOD 2: Instagram Download Sites"
echo "-----------------------------------"
echo "1. Go to: https://instgramdownloader.com or https://savefrom.net"
echo "2. Paste your Instagram post URLs one by one"
echo "3. Download each image"
echo "4. Rename them: hero-1.jpg, hero-2.jpg, etc."
echo ""
echo "METHOD 3: Gumroad & Big Cartel"
echo "-------------------------------"
echo "1. Visit your stores:"
echo "   - https://kancerthecrab.gumroad.com"
echo "   - https://kancerthecrabshop.bigcartel.com"
echo "2. Right-click on product images → 'Save Image As'"
echo "3. Save to: images/ folder"
echo ""
echo "METHOD 4: TROVE Wallet Collab"
echo "------------------------------"
echo "1. Visit: https://www.trove.cc/en-us/pages/artist/kancer-the-crab"
echo "2. Screenshot or save the wallet design images"
echo ""
echo "📁 FOLDER STRUCTURE"
echo "-------------------"
echo "kancer-the-crab/"
echo "├── images/"
echo "│   ├── hero-1.jpg    (for hero slideshow)"
echo "│   ├── hero-2.jpg"
echo "│   ├── hero-3.jpg"
echo "│   ├── hero-4.jpg"
echo "│   ├── strip-1.jpg   (for work strip)"
echo "│   ├── strip-2.jpg"
echo "│   └── ..."
echo "├── index.html"
echo "├── styles.css"
echo "└── script.js"
echo ""
echo "📝 NEXT STEPS"
echo "-------------"
echo "1. Create images/ folder: mkdir -p images"
echo "2. Download your images using methods above"
echo "3. Update the image URLs in index.html:"
echo "   - Hero slideshow: Search for 'hero-slideshow'"
echo "   - Work strip: Search for 'work-strip'"
echo "4. Replace placeholder URLs with your actual images:"
echo "   Change: url('https://images.unsplash.com/...')"
echo "   To:     url('images/hero-1.jpg')"
echo ""
echo "💡 PRO TIP: Use Canva or Photoshop to make all images"
echo "   the same aspect ratio (16:9 for hero, 3:2 for strip)"
echo ""
echo "For help, message me on WhatsApp or Instagram DM"
echo ""
